name: YellowChat
main: net.azisaba.yellowchat.YellowChat
version: @VERSION@
commands:
  yellowchat:
    permission: yellowchat.use_command
permissions:
  yellowchat.use_command:
    description: Allows you to use the /yellowchat command.
    default: true
  yellowchat.use:
    description: Allows you to use the YellowChat.
    default: false
  yellowchat.default_off:
    description: If true, the yellow chat feature is off by default.
    default: false
